version: '3'

services:
  db:
    image: postgres:13
    ports:
      - "5435:5432"
    volumes:
      - ./db_dimatech:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wl

  app:
    container_name: app
    build:
      context: .
    image: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8888:8888
    command: >
      sh -c "alembic upgrade head && python main.py app"
