version: '3'

services:
  db:
    image: postgres:13
    ports:
      - "5435:5432"
    volumes:
      - ./db_dimatech:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wl
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build:
      context: .
    image: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8888:8888
    command: "python main.py app"
