"""empty message

Revision ID: 68f7fe1cbbaf
Revises: ba48ffd43232
Create Date: 2025-03-23 21:06:55.165195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '68f7fe1cbbaf'
down_revision: Union[str, None] = 'ba48ffd43232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO "user" (email, password, role, created_at, updated_at) 
        VALUES 
            ('user', '50864922583b05271ab60f38dc7ce1dd108a7d6378cbb6f1825cedc5ecba19808ba28f67420f064be899cb7847fa08ce04557dc75778d76b1d6a36d7ffe72959', '0', '2025-01-01', '2025-01-01'),
            ('admin', '50864922583b05271ab60f38dc7ce1dd108a7d6378cbb6f1825cedc5ecba19808ba28f67420f064be899cb7847fa08ce04557dc75778d76b1d6a36d7ffe72959', '1', '2025-01-01', '2025-01-01');
    """)
    op.execute("""
    INSERT INTO wallet (balance, user_id, created_at, updated_at)
    VALUES (100, 1, '2025-01-01', '2025-01-01')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
